export const
  middlewares= Symbol.for("phased-middleware:middlewares"),
  Middlewares= middlewares,
  $middlewares= middlewares,
  name= Symbol.for("phased-middleware:name"),
  Name= name,
  $name= name,
  pipelines= Symbol.for("phased-middleware:pipelines"),
  Pipelines= pipelines,
  $pipelines= pipelines
