export const
  plugins= Symbol.for("phased-middleware:middlewares"),
  Plugins= plugins,
  $plugins= plugins,
  name= Symbol.for("phased-middleware:name"),
  Name= name,
  $name= name,
  phases= Symbol.for("phased-middleware:phases"),
  Phases= phases,
  $phases= phases,
  pipelines= Symbol.for("phased-middleware:pipelines"),
  Pipelines= pipelines,
  $pipelines= pipelines
